[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.5.21", features = ["derive"] }
colored = "2.1.0"
itertools = "0.13.0"
regex = "1.10.2"
serde = "1.0"
